type Article {
  id: ID!
  title: String!
  summary: String
  url: String
  links: [Article!]!
}

type Path {
  id: ID!
  title: String!
  startedAt: String!
  steps: [PathNode!]!
}

type PathNode {
  id: ID!
  article: Article
}

type Query {
  article(title: String!): Article
  searchArticles(query: String!): [Article!]!
  paths: [Path!]!
  path(id: ID!): Path
}

type Mutation {
  createPath(title: String!): Path!
  addStep(pathId: ID!, articleTitle: String!): Path!
  deletePath(id: ID!): Boolean!
}
