type Article {
  id: ID!
  title: String!
  summary: String!
  url: String!
  relatedArticles: [Article!]!
}

type Path {
  id: ID!
  title: String!
  startedAt: String!
  steps: [PathNode!]!
}

type PathNode {
  id: ID!
  position: Int!
  article: Article!
}

type Query {
  article(title: String!): Article
  searchArticles(query: String!): [Article!]!
  Paths: [Path!]!
  Path(id: ID!): Path
}

type Mutation {
  createPath(title: String!): Path!
  addStep(PathId: ID!, articleTitle: String!): Path!
  deletePath(id: ID!): Boolean!
}
